### ISSUE TITLE
question regarding MATCH option on creating Snowflake constraints

### ISSUE THREAD

**Issue by ciolo15** [Snowflake-Labs/dbt_constraints#53] opened 2023-07-28 08:58 UTC
I want to add a fk key constrint in my dbt model but the problem is that the column which has to be FK is not null and it is different than the referenced column ( pk in other table so not null).

I tested it in Snowflake and I saw that I can have the fk in this way only by using this script:

ALTER TABLE add constraint fk_something ( fk_key) references PK_table ( pk_key) MATCH SIMPLE RELY.

I checked the code but I did not see anything for the options ( MATCH FULL/SIMPLE/PARTIAL), I only saw that the generated code will be alter table ... RELY .

Thank you!

**Comment by sfc-gh-dflippo** [comment] 2023-07-28 19:45
I actually had to look up the MATCH SIMPLE syntax and meaning. I'm surprised that you are getting an error because I would expect a single nullable column FK to be OK with MATCH FULL, the default. MATCH FULL should mean for a multi-column FK that all columns in the child table should be nullable or not. Nevertheless, I am happy to add the syntax for MATCH SIMPLE because that is what I coded the FK test to allow. I will try to get the fix out shortly. I just want to try to recreate your error first and make sure my integration tests include the scenario.

**Comment by sfc-gh-dflippo** [comment] 2023-07-28 20:14
So, the odd thing is that I'm not getting an error in my testing for this, even when one of the two columns is nullable in the child. That is the scenario that MATCH FULL is supposed to get an error for. As far as I can see, Snowflake didn't care if a child column was null, only one of two columns is null, or if a child column is not null. I'm still OK adding the syntax but I can't explain how you have an error and I do not.

**Comment by homerunner-mqp** [comment] 2023-09-21 07:08
Sorry for re-opening, but the issue is more complicated than stated.
Snowflake fails silently when trying to create a foreign key between different schemas using MATCH SIMPLE. It goes through using MATCH FULL (default setting).

To actually get an error you have to change session variable UNSUPPORTED_DDL_ACTION to FAIL.

I can't reproduce the error stated in this question originally. Maybe having MATCH as a setting so it isn't hard-coded in the macro is an option?

**Comment by sfc-gh-dflippo** [comment] 2023-09-21 21:05
Now that we are seeing errors with this change, I'm going to back it out. I prefer to leave the FK DDL as the simple, default values with the one exception of `RELY`.

**Comment by choudrybabu** [comment] 2023-09-28 23:58
Any ETA on this @sfc-gh-dflippo

**Comment by sfc-gh-dflippo** [comment] 2023-10-18 20:31
I released the code in the last release so I'm closing this thread.

**Closed by sfc-gh-dflippo** 2023-10-18 20:31 UTC
Labels: bug
